# Generated by Django 5.1.4 on 2024-12-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=50, verbose_name='Name')),
                ('subcode', models.CharField(max_length=10, verbose_name='Code')),
                ('submarks', models.IntegerField(verbose_name='Marks')),
                ('subresult', models.CharField(max_length=4, verbose_name='Result')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
